apiVersion: v1
kind: Service
metadata:
  name: {{ include "kompasio-site.fullname" . }}-iframe
  annotations:
    {{- toYaml .Values.http.service.annotations | nindent 4 }}
  labels:
    {{- include "kompasio-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: iframe
spec:
  ports:
  - name: http
    nodePort: null
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    {{- include "kompasio-site.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http
  type: {{ toYaml .Values.http.service.type }}
